### ISSUE TITLE
app crashes when trying to upload a profile picture

### ISSUE THREAD

**Issue by david-r-edgar** [projectwife/mtesitoo-android#75]
I created a new account through the app, and now log in to try and upload a profile picture.
I choose to select an image from the gallery.
When I click on the image to select it, the app crashes, saying "Unfortunately, Tesitoo has stopped."

It also crashes with the same message when I choose "Add an image".

Device: Moto G3, Android 5.1.1

**Comment by ptyagicodecamp** [comment]
quick question: do you see the similar crash while taking new picture as well or just when you try to select image from gallery ?

**Comment by david-r-edgar** [comment]
Yes, I can't do either. The gallery one displays the gallery, and crashes
when I try and select. The taking a picture one crashes immediately.

**Comment by ptyagicodecamp** [comment]
@david-r-edgar I tried to re-produce this crash on emulator - API 22/Android-5.1, but it worked just fine. It could be a particular device issue may be. I would need error logs to diagnose this bug. There're few apps out there which can get logcat trace. Few examples are:  https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=en and https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=en. 

These tools have to be installed on device and reproduce crash to collect logs.

**Comment by david-r-edgar** [comment]
I tested on an Xperia P, Android 4.1.2.

Uploading an image from the gallery succeeded. Adding a new image failed, like before.

**Comment by david-r-edgar** [comment]
@ptyagicodecamp I had no problem reproducing this on the emulator.

Using a Nexus 7 (2012) with Android 5.1

Here is the log when trying to select a profile image from the gallery:

[profileImageFromGalleryErrorLog.txt](https://github.com/projectwife/mtesitoo-android/files/905381/profileImageFromGalleryErrorLog.txt)

**Comment by david-r-edgar** [comment]
and here's the log when adding an image:

[profileImageFromCameraErrorLog.txt](https://github.com/projectwife/mtesitoo-android/files/905394/profileImageFromCameraErrorLog.txt)

**Comment by ptyagicodecamp** [comment]
@david-r-edgar Yes, I can reproduce this crash on Nexus 7 (2012) with Android 5.1 emulator as well. Thanks a lot for details. Very helpful !

**Comment by ptyagicodecamp** [comment]
[UPDATE]
I see this crash happening consistently while taking new picture on all devices. Looks like a bug has been introduced while merging other branches. looking into it.

**Comment by ptyagicodecamp** [comment]
PR: https://github.com/projectwife/mtesitoo-android/pull/87

**Comment by ptyagicodecamp** [comment]
Fixed and merged in master.

**Comment by david-r-edgar** [comment]
Retested on latest version.
On same device, Moto G3, Android 5.1.1
Issue still occurs - both for image from camera and for image from gallery.

**Comment by david-r-edgar** [comment]
still seen as of 14th Jan 2018 version on play store
